// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';



// Supabase Replica URL and Key
const SUPABASE_URL = "https://kvqarbdczfdxgviafggz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cWFyYmRjemZkeGd2aWFmZ2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTkwODgsImV4cCI6MjA2OTQzNTA4OH0.MEsN787XyCy6T78eLOvhw-SnchcExy7U1LhPykxIC5A";
const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cWFyYmRjemZkeGd2aWFmZ2d6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzg1OTA4OCwiZXhwIjoyMDY5NDM1MDg4fQ.vJuXckA6_uhyAC1So7znCkemvzOBISf0FSNdsQTWZHk"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export const supabaseAdmin = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_KEY);
