// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvznqtzwmlyrpjuqxuiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2em5xdHp3bWx5cnBqdXF4dWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzEwNTgsImV4cCI6MjA2NjQ0NzA1OH0.qnSHfFiTk4Cj1kfDbV-AJ9-j03Se04UO532o_pWqgOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);